default_server = "maincloud"
spacetimedb_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJoZXhfaWRlbnRpdHkiOiJjMjAwZWIwODc4ZGQ1NjBhZTEzZmUxMTk3MTQ5ZTE2MzRhMDFkYjJiODE5YzhlY2M2NTdjM2YyNzk3YWRkMWEyIiwic3ViIjoiNzIwZTA4NmEtMTA0ZS00ZWE3LWEyMzMtYTI2N2E0NjFmYTYxIiwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjpbInNwYWNldGltZWRiIl0sImlhdCI6MTc3NzczOTEzNiwiZXhwIjpudWxsfQ.yUaMry7XX8WY1e0noLRwWNvD63QmGRR3ZJIzj9x3mk-F3fzix-mO77S-cUFBboEScOnnGXZNf99JWlHbddKYrQ"

[[server_configs]]
nickname = "maincloud"
host = "maincloud.spacetimedb.com"
protocol = "https"

[[server_configs]]
nickname = "local"
host = "127.0.0.1:3000"
protocol = "http"
